=== mamedev/mame/trunk/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT software (description, year?, publisher, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea databits (8|16|32|64) "8">
				<!ATTLIST dataarea endian (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== mamedev/mame/hash/photo_cd.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0

http://redump.org/discs/system/photo-cd/
-->
<softwarelist name="photo_cd" description="Kodak Photo CD images (Beige Book)">

	<software name="toilhana" supported="no">
		<!-- http://redump.org/disc/103991/ -->
		<description>Toilet no Hanako-san (Japan)</description>
		<year>1995</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="alt_title" value="トイレの花子さん" />
		<info name="serial" value="PCD0924" />
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="toilet_no_hanako-san_(japan)" sha1="bb35be781dcf134f1225df7352f8bcac1ab11629"/>
			</diskarea>
		</part>
	</software>

	<software name="winsenna" supported="no">
		<!-- http://redump.org/disc/103998/ -->
		<description>Winning Run: Ayrton Senna: 20-nen no Kiseki (Japan)</description>
		<year>1995</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="alt_title" value="ＷＩＮＮＩＮＧ ＲＵＮ アイルトン・セナ ２０年の軌跡" />
		<info name="barcode" value="T4934878151235" />
		<info name="serial" value="PCD0806" />
		<part name="cdrom" interface="cdrom">
			<diskarea name="cdrom">
				<disk name="winning_run_-_ayrton_senna_-_20-nen_no_kiseki_(japan)" sha1="0bf605a8e5713f5802f827424507f53e65f586e7"/>
			</diskarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/p2000_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0
-->
<softwarelist name="p2000_cart" description="P2000T/M ROM cartridges">

	<software name="basic">
		<description>Philips Cassette basic V1.1 P2305</description>
		<year>1981</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="basic.rom" size="16384" crc="9d9d38f9" sha1="fb5100436c99634a2592a10dff867f85bcff7aec"/>
			</dataarea>
		</part>
	</software>

    <software name="basic24">
		<description>Philips Disk Basic V2.4 P2306/P2311</description>
		<year>1981</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Basic-24.BIN" size="16384" crc="6CB8E392" sha1="A2A0956C409ED1143604941F601D32372C0E04FB"/>
			</dataarea>
		</part>
	</software>

	<software name="jwsbasic">
		<description>Philips Cassette basic with JWS boot loader</description>
		<year>1986</year>
		<publisher>J.W.Strikkers</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="jwsbasic.rom" size="16384" crc="7b7aedab" sha1="f5a0c98c2794b1288ab39ce2f25623fa425bbf6d"/>
			</dataarea>
		</part>
	</software>

    <software name="zemon">
		<description>Zemon Z80 Assembler V1.4</description>
		<year>1985</year>
		<publisher>F.Jalvingh &amp; L.Hilgersom</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Zemon 1.4.bin" size="16384" crc="912c7455" sha1="53bf77ff64a113c289fcba0529195e1cfc3e383e"/>
			</dataarea>
		</part>
	</software>

	<software name="text2000v2">
		<description>Text 2000 tekstverwerker V2.0</description>
		<year>1984</year>
		<publisher>Philips Gebruikersgroep</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Text2000 2.bin" size="12288" crc="2B6B56D8" sha1="D2626E88AEDD1651E25791498A72CD31CF47FDF6"/>
			</dataarea>
		</part>
	</software>

	<software name="text2000">
		<description>Text 2000 tekstverwerker V3.0</description>
		<year>1984</year>
		<publisher>Philips Gebruikersgroep</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Text2000 3.bin" size="16384" crc="C05E0473" sha1="5919B18B7DAF830377C84D1FFFF553D821A7960F"/>
			</dataarea>
		</part>
	</software>

    <software name="familiegeheugenV2">
		<description>Philips Familiegeheugen 2.0 NL P2304</description>
		<year>1984</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="familiegeheugen 2.bin" size="16384" crc="7B1D922A" sha1="CF8501C679952FCE06ACCAFD6ECE2591F68CD70D"/>
			</dataarea>
		</part>
	</software>

    <software name="familiegeheugenV3">
		<description>Philips Familiegeheugen 3.L NL P2304</description>
		<year>1986</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="familiegeheugen 3.bin" size="16384" crc="A4C5D1C1" sha1="8FB8EB7A34662C7888878B6E05AED64559E37A79"/>
			</dataarea>
		</part>
	</software>

    <software name="familiegeheugen">
		<description>Philips Familiegeheugen 4.L NL P2304</description>
		<year>1987</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="familiegeheugen 4.bin" size="16384" crc="AE114624" sha1="3AEBCD396A1870FF21E574B46A8E67FABC67624D"/>
			</dataarea>
		</part>
	</software>

    <software name="assemblerV56">
		<description>Assembler V5.6</description>
		<year>1984</year>
		<publisher>Ron Eijnthoven</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="assembler 5.6.bin" size="16384" crc="1AB4F488" sha1="4606C775B333D394A304986FFFCA82FE6CFA0C98"/>
			</dataarea>
		</part>
	</software>

    <software name="assembler">
		<description>Assembler V5.9</description>
		<year>1987</year>
		<publisher>Ron Eijnthoven</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="assembler 5.9.bin" size="16384" crc="A50E0E68" sha1="89AE3BAFACF8E7109E7B8ACD0BC9D346161D0D15"/>
			</dataarea>
		</part>
	</software>

    <software name="bis">
		<description>BIS Terminal Program</description>
		<year>1981</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="BIS.bin" size="16384" crc="B9E6B089" sha1="415EBE69E953FEB56A7132E0E66478ED82797902"/>
			</dataarea>
		</part>
	</software>

    <software name="cpm">
		<description>CPM Nater</description>
		<year>198?</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="CPM Nater.bin" size="16384" crc="3B1F4D1E" sha1="73DE7C2D9B9144E48A1171C233B3B84BB849CC30"/>
			</dataarea>
		</part>
	</software>

    <software name="dagmarkt">
		<description>Dagmarkt P2000 Databank programma voor M2009</description>
		<year>1986</year>
		<publisher>F.L. van der Markt</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="dagmarkt.bin" size="16384" crc="BA8BA3CE" sha1="6E8E85609EBFC6F0D698CA25126150A6E2416D15"/>
			</dataarea>
		</part>
	</software>

    <software name="programmer">
		<description>EEPROM-programmer</description>
		<year>198?</year>
		<publisher>NA</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="EPROM-programmer.bin" size="12288" crc="64112DBE" sha1="8ECDF7FD65D06C6E1931720E141315C2C17E44FB"/>
			</dataarea>
		</part>
	</software>

    <software name="flexbase">
		<description>Flexbase 2.1</description>
		<year>198?</year>
		<publisher>NA</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="flexbase.bin" size="16384" crc="6C7B788B" sha1="2F82A760A64B551A82FD2F7264BED3762F21C510"/>
			</dataarea>
		</part>
	</software>

    <software name="forth">
		<description>Forth-3.0 V1.4</description>
		<year>1986</year>
		<publisher>F.L.van der Markt</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Forth.bin" size="10496" crc="345DF79C" sha1="73EF669E06522673102488A92DDFD2D0F3239B39"/>
			</dataarea>
		</part>
	</software>

    <software name="maintenance1">
		<description>Maintenance 1</description>
		<year>198?</year>
		<publisher>NA</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Maintenance 1.bin" size="12288" crc="711E96D4" sha1="FD8D9EDA5941179D3F4DAD831F636E5036AFC958"/>
			</dataarea>
		</part>
	</software>

    <software name="maintenance2">
		<description>Maintenance v2.2</description>
		<year>198?</year>
		<publisher>NA</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="Maintenance 2.bin" size="16384" crc="3EABA205" sha1="022A4C8C5E18F2566CC12A6304F5800CA95D613E"/>
			</dataarea>
		</part>
	</software>

    <software name="nebocalc">
		<description>NeboCalc</description>
		<year>1980</year>
		<publisher>Regents of the University of California</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="NeboCalc.bin" size="16384" crc="1359824A" sha1="85FF8F90C7DCDBE8C5FC0AF1F31324C1196D8683"/>
			</dataarea>
		</part>
	</software>

    <software name="tekstverwerker">
		<description>Tekstverwerker TV1.0</description>
		<year>198?</year>
		<publisher>NA</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="tekst 1.bin" size="16384" crc="66B2BC1E" sha1="AA1A231DEC43B187225D735D0FF9C031AD0A0ABB"/>
			</dataarea>
		</part>
	</software>

    <software name="pascal">
		<description>UCSD Pascal</description>
		<year>1980</year>
		<publisher>Regents of the University of California</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="UCSD Pascal.bin" size="16384" crc="58A11897" sha1="50C405F39C084BC7346206907B3F8BCEC2A2B8A0"/>
			</dataarea>
		</part>
	</software>

    <software name="wordprocessor1">
		<description>WordProcessor WP1.2</description>
		<year>198?</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="WordProcessor 1.bin" size="16384" crc="563BAFC9" sha1="93A13CA028966583B960DAFA758B9FF5E2980E17"/>
			</dataarea>
		</part>
	</software>

    <software name="wordprocessor">
		<description>WordProcessor WP2</description>
		<year>198?</year>
		<publisher>Philips</publisher>
		<part name="slot1" interface="p2000_cart">
			<dataarea name="rom" size="16384">
				<rom name="WordProcessor 2.bin" size="16384" crc="3B89EE86" sha1="DA8EC1A9B78660139EBD5C405A350210F0529644"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/spectrum_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<!-- ZX Spectrum Disc images
    for +3 machines etc.
-->


<softwarelist name="spectrum_flop" description="ZX Spectrum Disc Images">
	
	<software name="pacmania" >
		<description>Pac-Mania (Europe / Australia)</description>
		<year>1988</year>
		<publisher>Namco / Grandslam</publisher>
		<part name="flop1" interface="floppy_3">
			<dataarea name="flop" size="195328">
				<rom name="pac-mania.dsk" size="195328" crc="88f5506b" sha1="827c95935dd3a1dd919989fc6d7a0efa4e5aebc1" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/ibm5150_demos.xml
<?xml version="1.0" ?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="ibm5150_demos" description="IBM PC floppy disk (demoscene)">

	<software name="8088mph" supported="no">
		<description>8088 MPH (Final Version)</description>
		<year>2015</year>
		<publisher>Hornet + CRTC + DESiRE</publisher>
		<notes><![CDATA[
Prints "Metric cycle count of 1127 deviates 33%" with ibm5160
Various GFX glitches, cfr. https://youtu.be/hNRO7lno_DM for side by side test
Hangs at credits screen
]]></notes>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size = "368640">
				<rom name="8088mph final.360" size="368640" crc="a30504e8" sha1="5f637b83dca774b7104fed0d20195dd769e0838b"/>
			</dataarea>
		</part>
	</software>

	<software name="8088mphp" cloneof="8088mph" supported="no">
		<description>8088 MPH (Revision 2015 Party version)</description>
		<year>2015</year>
		<publisher>Hornet + CRTC + DESiRE</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size = "368640">
				<rom name="8088mph.360" size="368640" crc="4f5f4871" sha1="b7f61ad133edf7e80d2ccd0bc7767baf0b13f34d"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/mbc55x.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<softwarelist name="mbc55x" description="Sanyo MBC-550 and MBC-555 disk images">

	<software name="msdos211">
		<description>MS-DOS v2.11</description>
		<year>198?</year>
		<publisher>Sanyo / Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="microsoft ms-dos 2.11 (sanyo).img" size="368640" crc="b64b0c3c" sha1="35a9a1e62ccefa3c66d912b4d58c1a132cd757d2" status="baddump" />
			</dataarea>
		</part>
	</software>

	<software name="msdos211a" cloneof="msdos211">
		<description>MS-DOS v2.11 (Alt?)</description>
		<year>198?</year>
		<publisher>Sanyo / Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_ms-dos_2.11.ima" size="368640" crc="ab9dd1d4" sha1="eb5a5dd025e0e8efacea603daf37243986d92262"/>
			</dataarea>
		</part>
	</software>

	<software name="msdos125">
		<description>MS-DOS v1.25</description>
		<year>198?</year>
		<publisher>Sanyo / Microsoft</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="163840">
				<rom name="msdos125" size="163840" crc="1ea744cc" sha1="dd8b41bb67d0b888cd70ded4b61701708caa5dac"/>
			</dataarea>
		</part>
	</software>

	<software name="calcstar">
		<description>Calcstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_calcstar.ima" size="368640" crc="422ff754" sha1="4d09a213d4a0dd2bdb26398beaed9bce070abbcd"/>
			</dataarea>
		</part>
	</software>

	<software name="datastar">
		<description>Datastar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_datastar.ima" size="368640" crc="93cad6c5" sha1="5e4ba8deb3995c57e37eda9f06841daff15b0e17"/>
			</dataarea>
		</part>
	</software>

	<software name="easydraw">
		<description>Easy Draw</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_easydraw.ima" size="368640" crc="e6c1ad15" sha1="d1e392b04a966264114d7965fd18a0a4742fa85c"/>
			</dataarea>
		</part>
	</software>

	<software name="larn">
		<description>Larn</description>
		<year>1986</year>
		<publisher>Noah Morgan</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="larn.img" size="368640" crc="a57add87" sha1="696a0fb800d89d59a22381ddd399f1548fbd3646"/>
			</dataarea>
		</part>
	</software>

	<software name="picasso">
		<description>Picasso</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="picasso.img" size="368640" crc="b4dad321" sha1="3d5555f5d7d6f49bb51e334c86783611dc131e06"/>
			</dataarea>
		</part>
	</software>

	<software name="spelstar">
		<description>Mailmerge Spelstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_mailmerge_spelstar.ima" size="368640" crc="d555bebb" sha1="44de7c054533d5eac7db8802facfda3eea70a1f2"/>
			</dataarea>
		</part>
	</software>

	<software name="rprtstar">
		<description>Reportstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_reportstar.ima" size="368640" crc="2992d3a1" sha1="75d589d777c00db7c8364353817947d4ac95c582"/>
			</dataarea>
		</part>
	</software>

	<software name="softse05">
		<description>Soft Sector Disk 05</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="softse05.img" size="368640" crc="a5252da6" sha1="a840d6e2ef9aa840898cd02ec0eca217b1abef3d"/>
			</dataarea>
		</part>
	</software>

	<software name="wordstar">
		<description>Wordstar</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_wordstar.ima" size="368640" crc="71c29f9a" sha1="389215fbfab4c1e218d8ef08fa5f7c2bb2a4e6da"/>
			</dataarea>
		</part>
	</software>



	<software name="basgames">
		<description>Basic Games</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="sanyo_mbc555_basic_games.ima" size="368640" crc="e076efa4" sha1="a9fd7dcae96aca09206a4a8529e50cdb191739ba"/>
			</dataarea>
		</part>
	</software>

	<software name="cashman">
		<description>Cashman</description>
		<year>1984</year>
		<publisher>Michtron</publisher>
		<info name="programmer" value="Bill Dunlevy" />
		<info name="release" value="198401xx" />

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="34844">
				<rom name="cashman.td0" size="34844" crc="baecaef3" sha1="0a17be5ea8864e6bc9074acbea39d28a2828d53d"/>
			</dataarea>
		</part>
	</software>

	<software name="demonsd">
		<description>Demon Seed</description>
		<year>1984</year>
		<publisher>Michtron</publisher>
		<info name="programmer" value="Phil Mackenzie " />
		<info name="programmer" value="Jeff Sorensen" />

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="29464">
				<rom name="demonsd.td0" size="29464" crc="11d9577b" sha1="15a5927809aa5762a6289386935d1a2c24e8d239"/>
			</dataarea>
		</part>
	</software>

<!-- contains Zork 1, 2 and 3 -->
	<software name="zork">
		<description>Zork Compilation</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="zork.dsk" size="368640" crc="9b7daf44" sha1="34ca63dde2b4a85bac2e6391ca4d588e06058039"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== mamedev/mame/hash/octopus.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="octopus" description="LSI Octopus floppy disk images">

	<software name="diag">
		<description>Octopus Diagnostic Disk</description>
		<year>198?</year>
		<publisher>LSI</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="217527">
				<rom name="octdiag.imd" size="217527" crc="8366eb38" sha1="50689555508351e268a7f5ab5569a298768d7573"/>
			</dataarea>
		</part>
	</software>

	<software name="msdos211">
		<description>MS-DOS v2.11</description>
		<year>1983</year>
		<publisher>LSI / Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="203952">
				<rom name="octmsdos.imd" size="203952" crc="20921e6d" sha1="28ac96c7f8b0855309f9d8bbff29974b1e74bfa6"/>
			</dataarea>
		</part>
	</software>

	<software name="cdos41">
		<description>Concurrent DOS v4.1</description>
		<year>198?</year>
		<publisher>LSI / Digital Research</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="292255">
				<rom name="octcd411.imd" size="292255" crc="6099fb99" sha1="84f8174a9f23215af9cc33aa16781e96e9a5b836"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="362833">
				<rom name="octcd412.imd" size="362833" crc="e3fbde01" sha1="0d47bd2d570ce0495d59eab0bf97981438a13e44"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="322953">
				<rom name="octcd413.imd" size="322953" crc="8fbeac42" sha1="5cfbe41d874b528d45378697cf850f16fb6bdc14"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="158250">
				<rom name="octcd414.imd" size="158250" crc="3a44bfd9" sha1="7daa294df18029f09040879c2697fafd54e615ee"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="310680">
				<rom name="octcd415.imd" size="310680" crc="ce13d027" sha1="ccd888b22db4e5f051707192af38d4aa25672ac3"/>
			</dataarea>
		</part>
		<part name="flop6" interface="floppy_5_25">
			<dataarea name="flop" size="164406">
				<rom name="octcd416.imd" size="164406" crc="dda2eb61" sha1="f9fad795f3830454df609701624e0b852f19c5fd"/>
			</dataarea>
		</part>
		<part name="flop7" interface="floppy_5_25">
			<dataarea name="flop" size="163383">
				<rom name="octcd417.imd" size="163383" crc="62f1707c" sha1="5837acbfcd6b5545d432cdaa6d6d023844bd944c"/>
			</dataarea>
		</part>
	</software>

	<software name="cdos52">
		<description>Concurrent DOS v5.2</description>
		<year>1987</year>
		<publisher>LSI / Digital Research</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="267678">
				<rom name="octcd521.imd" size="267678" crc="8f7d6f1d" sha1="491f1bcb99cec3d95de9c5ee6e5c95fab19b534c"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="325980">
				<rom name="octcd522.imd" size="325980" crc="be76fb95" sha1="6d260edc67441f6446e137fcc0e2d8b88b19f254"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="330072">
				<rom name="octcd523.imd" size="330072" crc="b91c30f9" sha1="fb5a38c7d8ce4ad20126644d6a85d70f55f81703"/>
			</dataarea>
		</part>
	</software>

</softwarelist>
