=== mamedev/mame/trunk/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT software (description, year?, publisher, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea databits (8|16|32|64) "8">
				<!ATTLIST dataarea endian (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== mamedev/mame/hash/bbc_hdd.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0
-->

<softwarelist name="bbc_hdd" description="Acorn BBC Micro hard disks">

	<software name="cf_v103">
		<description>Master 128 ADFS Hard Drive Image V1.03</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="M" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_v103" sha1="380b817645fcbea317973db59f10db5120e8ac44" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_v105">
		<description>Master 128 ADFS Hard Drive Image V1.05</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="M" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_v105" sha1="9980aee632803ae4986b7ef56e2020a09ddde2b6" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_b106e">
		<description>Model B ADFS Hard Drive Image B1.06e</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_b106en" sha1="f7cb1132c78a1c742661a0bf6366dc7e8139fe96" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_t107">
		<description>Model B ADFS Hard Drive Image T1.07</description>
		<year>2009</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf1gb_t107" sha1="b6daa6b1973e762ed61b153845a8dfb26d7b0271" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_b131r">
		<description>Model B ADFS Hard Drive Image B1.31 (Retro Software)</description>
		<year>2010</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf_b131r" sha1="b921e3d5d5d359af7be6626fd928754ecf19a7ff" writeable="yes" />
			</diskarea>
		</part>
	</software>

	<software name="cf_b142">
		<description>Model B ADFS Hard Drive Image B1.42</description>
		<year>2010</year>
		<publisher>RetroClinic</publisher>
		<sharedfeat name="compatibility" value="B" />
		<part name="hdd" interface="ide_hdd">
			<diskarea name="harddriv">
				<disk name="bbc_cf_b142" sha1="1f155b6bf1730c070314adf7387baf891476a668" writeable="yes" />
			</diskarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/aim65_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="aim65_cart" description="Rockwell AIM 65 cartridges">

<!--

  There are 5 ROM sockets on the AIM 65 PCB: 2 sockets were for the boot strap and 3 sockets for software roms,
  at locations z24, z25, and z26.

  There are the BASIC ROMs, PL65 and FORTH. Each has 2 ROMs and they all work.

  The Assembler ROM works. The Mathpack does not work (it needs another ROM which is missing).

-->

	<software name="assemblr">
		<description>Assembler</description>
		<year>197?</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load in &quot;cart3&quot;, then press N to start"/>

		<part name="cart" interface="aim65_cart">
			<dataarea name="z24" size="4096">
				<rom name="assembler.z24" size="4096" crc="0878b399" sha1="483e92b57d64be51643a9f6490521a8572aa2f68" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="basic11">
		<description>AIM 65 BASIC v1.1</description>
		<year>1978</year>
		<publisher>Microsoft</publisher>
		<info name="usage" value="Load both in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="cart" interface="aim65_cart">
			<dataarea name="z25" size="4096">
				<rom name="basic.z25" size="4096" crc="d7b42d2a" sha1="4bbdb28d332429825adea0266ed9192786d9e392" offset="0x0000" />
			</dataarea>

			<dataarea name="z26" size="4096">
				<rom name="basic.z26" size="4096" crc="36a61f39" sha1="f5ce0126cb594a565e730973fd140d03c298cefa" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="forth13">
		<description>AIM 65 FORTH v1.3</description>
		<year>197?</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load both in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="cart" interface="aim65_cart">
			<dataarea name="z25" size="4096">
				<rom name="forth v1.3.z25" size="4096" crc="0671d019" sha1="dd2a1613e435c833634100cf4a22c6cff70c7a26" offset="0x0000" />
			</dataarea>

			<dataarea name="z26" size="4096">
				<rom name="forth v1.3.z26" size="4096" crc="a80ad472" sha1="42a2e8c86829a2fe48090e6665ff9fe25b12b070" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="mathpack" supported="no">
		<description>Mathpack</description>
		<year>197?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cart" interface="aim65_cart">
			<dataarea name="z24" size="4096">
				<rom name="mathpack.z24" size="4096" crc="4889af55" sha1="5e9541ddfc06e3802d09b30d1bd89c5da914c76e" offset="0x0000" />
			</dataarea>
		</part>
	</software>

	<software name="pl65">
		<description>AIM 65 PL/65 v1.0</description>
		<year>1978</year>
		<publisher>Rockwell</publisher>
		<info name="usage" value="Load both in &quot;cart1&quot; and &quot;cart2&quot;, then press 5 to start"/>

		<part name="cart" interface="aim65_cart">
			<dataarea name="z25" size="4096">
				<rom name="pl65 v1.0.z25" size="4096" crc="76dcf864" sha1="e937c54ed109401f796640cd45b27dfefb76667e" offset="0x0000" />
			</dataarea>

			<dataarea name="z26" size="4096">
				<rom name="pl65 v1.0.z26" size="4096" crc="2ac71abd" sha1="6df5e3125bebefac80d51d9337555f54bdf0d8ea" offset="0x0000" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/sd132_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="sd132_flop" description="Ensoniq SD-1 32 Voice Disk Images">

	<software name="os400" cloneof="os410" supported="yes">
		<description>SD-1 Sequencer OS version 4.00</description>
		<year>1991</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SD1_OS_4_00.img" size="819200" crc="e218f989" sha1="6ba14f4ff2ad99800478893716d9c14a61a7eb38" />
			</dataarea>
		</part>
	</software>

	<software name="os410" supported="yes">
		<description>SD-1 Sequencer OS version 4.10</description>
		<year>1992</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SD1_OS_4_10.img" size="819200" crc="82fb69a4" sha1="152a1147ccb0424a9e8d96ca948c085fadcaf361" />
			</dataarea>
		</part>
	</software>

	<software name="sd1_32_demo1" supported="yes">
		<description>SD-1 32 Voice Demo Disk #1</description>
		<year>1992</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SD1_32Voice_DemoDisk1.img" size="819200" crc="7cfb73c5" sha1="0e5f8a3b64674d56d40346e62f7a095ace83bb55" />
			</dataarea>
		</part>
	</software>

	<software name="multi_demo1" supported="yes">
		<description>Multi-Product Demo Disk #1</description>
		<year>1992</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="MultiProductDemoDisk1.img" size="819200" crc="2a5456a1" sha1="c9ab9199fac474c01751ba0d1678dcd72ff57834" />
			</dataarea>
		</part>
	</software>

	<software name="multi_demo2" supported="yes">
		<description>Multi-Product Demo Disk #2</description>
		<year>1993</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="MultiProductDemoDisk2.img" size="819200" crc="4f017eaf" sha1="65f3734cfab0fd79ec192674383be7b76e45d5b3" />
			</dataarea>
		</part>
	</software>

	<software name="sq32_demo1" supported="yes">
		<description>SQ 32 Voice Demo Disk #2</description>
		<year>1993</year>
		<publisher>Ensoniq</publisher>

		<part name="flop" interface="floppy_3_5">
			<dataarea name="flop" size="819200">
				<rom name="SQ_32Voice_DemoDisk1.img" size="819200" crc="91ba0cc0" sha1="c7e3f803122ce9b8b860724a064c40bd9747da41" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/k28.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->

<!--

Known modules:

1st series:
- Spelling I: VSM: 16KB CM62086
- Spelling II: VSM: 16KB CM6????
- Spelling III: VSM: 16KB CM62087
- other: ?

2nd series:
- Spelling 1 (Expansion Module 1): VSM: 16KB CM6????
- Spelling 2 (Expansion Module 2): VSM: 16KB CM62216
- Spelling 3 (Expansion Module 3): VSM: 16KB CM62215
- Spelling 4 (Expansion Module 4): VSM: 16KB CM62217
- Sentence Superstars (Expansion Module 5): VSM: 16KB CM6????
- Vowel Detectives (Expansion Module 6): VSM: 16KB CM62219

For the 2nd series, the first 4 are (C) Tiger Electronics, modules 5 and 6 are
(C) Coleco Industries. The cartridge labels don't show the title, but simply say
"Expansion Module x" where x = 1-6.

It is assumed that the 1st series Spelling modules are the same as the Expansion
modules. CM62215 was confirmed to be the same as CM62087.

-->

<softwarelist name="k28" description="K-2-8 (model 7-232) modules">

	<software name="spell1">
		<description>Spelling 1 (Expansion Module 1)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8111"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62086" size="0x4000" crc="0349798b" sha1="afdad242f9c7dec0c5fd83670e3d8f1637140e76" />
			</dataarea>
		</part>
	</software>

	<software name="spell2">
		<description>Spelling 2 (Expansion Module 2)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8112"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62216" size="0x4000" crc="1c99306f" sha1="7bfadeec79bdc231c4e3447149e2f6542cfe077d" />
			</dataarea>
		</part>
	</software>

	<software name="spell3">
		<description>Spelling 3 (Expansion Module 3)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8113"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62215" size="0x4000" crc="f2deb9a2" sha1="9fb264b869d1298ebd76811931bed83ac122fe4b" />
			</dataarea>
		</part>
	</software>

	<software name="spell4">
		<description>Spelling 4 (Expansion Module 4)</description>
		<year>1985</year>
		<publisher>Tiger Electronics</publisher>
		<info name="serial" value="8114"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62217" size="0x4000" crc="995936b2" sha1="8bd0fea4ade9972d1d6cb521f9367c971c7eead6" />
			</dataarea>
		</part>
	</software>

	<software name="vdetect">
		<description>Vowel Detectives (Expansion Module 6)</description>
		<year>1987</year>
		<publisher>Coleco</publisher>
		<info name="serial" value="8116"/>
		<part name="cart" interface="k28">
			<dataarea name="rom" size="0x4000">
				<rom name="cm62219" size="0x4000" crc="177b5cb5" sha1="2ed44fea8f931fc8aa46dafdda1c6c30b8c9dc01" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/pc8001mk2_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="pc8001mk2_flop" description="NEC PC-8001mkII (N80 BASIC) disk images">
<!--

Known list of SW released for the system (all cassette releases?):
kanji name, romaji name, manufacturer, release date in %MMM %YY format, notes
スターフリート, Star Fleet, Tecno Soft, May 83,
PCジャンmkII, PC-Jong! mkII, Compaq, Sep 83, (Adds color to regular PC-Jong)
Bon Bon, Bon Bon, Compaq, Aug 83, Aug 83,
モンスターハウス, Monster House, Compaq, Jul 83,
四次元の家, 4 Dimension House, Prosumer, Nov 83,
(these are unconfirmed if being specifically for PC-8001mkII or works on vanilla PC-8001 too)
クイズダービー, Quiz Derby, Takara, Dec 83, (based off the TBS show)
タンクトップ, Tank Top, Magical Zoo, Dec 83,
グラフィック雀球, <Graphic Mahjong?> , ストラッドフォード, Dec 83, (description clearly claims to be a mahjong)

-->

<!-- !Operating Systems -->

	<software name="n80diskb" supported="no">
		<description>N80 Disk BASIC</description>
		<year>1983</year>
		<publisher>NEC / Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="348848">    <!-- Data CRC16: 18249 -->
				<rom name="n-basic.d88" size="348848" crc="0ed0a4c8" sha1="2e80b0b4fc38eb1f81fd27f6828249c764091a55"/>
			</dataarea>
		</part>
	</software>

	<software name="pc80sys" supported="no">
		<description>PC-8001mkII System Disk</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="348832">    <!-- Data CRC16: 51389 -->
				<rom name="pc-8001mkii system disk.d88" size="348832" crc="3fc9a80e" sha1="8e65e5b7376799553bbc3ae41223b36c7e807cee"/>
			</dataarea>
		</part>
	</software>

	<!-- TODO: alt of above? -->
	<software name="n80mkii" supported="no">
		<description>N-80 BASIC system disk</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="[os] n80 basic system disk (pc-8001mkii).d88" size="348848" crc="ff9416a4" sha1="3321c6a723545ef7f413a372683a1e40ef7ea4ef"/>
			</dataarea>
		</part>
	</software>

	<software name="n80mkiia" cloneof="n80mkii" supported="no">
		<description>N-80 BASIC system disk (alt)</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="[os] n80 basic system disk (pc-8001mkii) [alt 1].d88" size="348848" crc="452088aa" sha1="991dad9039b17ff3b1c5c234e47c96f1068cce53"/>
			</dataarea>
		</part>
	</software>

<!-- !Games -->

	<software name="cranstonmk2" supported="no">
		<description>Cranston Manor</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<!-- TODO: "run MK2" ? -->
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="344496">
				<rom name="cranston manor (mkii) (disk 1) {run mk2}.d88" size="344496" crc="cae808d0" sha1="27a3f9d322217fb6f9c00c8056bc9a79419e484c"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="cranston manor (mkii) (disk 2).d88" size="348848" crc="e1f04287" sha1="1fb1f14763b97058bc19c6bc18bb075f99baee85"/>
			</dataarea>
		</part>
	</software>

	<software name="ulyssesmk2" supported="no">
		<description>Ulysses and the Golden Fleece</description>
		<year>1983</year>
		<publisher>スタークラフト (Starcraft)</publisher>
		<info name="alt_title" value="ユリシーズ"/>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="344496">
				<rom name="ulysses (mkii) (disk 1).d88" size="344496" crc="c8cda3c8" sha1="3afe306f81b0a031ac3847567951cd3ec70f9dbd"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="ulysses (mkii) (disk 2).d88" size="348848" crc="afc8ea36" sha1="a80ad911aeaea4bc6f903d87ce8d66abdcfc318f"/>
			</dataarea>
		</part>
	</software>

<!-- !Collections -->

	<software name="gamepc" supported="no">
		<description>Game-PC (Collection)</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="31424">
				<rom name="[os] game-pc (mkii).d88" size="31424" crc="a2f5c72e" sha1="702734c1f92f7a765db2b49a1a67215ff9ba662d"/>
			</dataarea>
		</part>
	</software>


<!-- !Utilities -->

	<software name="n80n88" supported="no">
		<description>N80 and N88 Disk BASIC Utility Collection</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<notes><![CDATA[
flop5: "Incorrect layout on track 0 head 0, expected_size=50000, current_size=68144"
]]></notes>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="348304">
				<rom name="[utility] n80 and n88 disk basic utility collection (disk 1 - n mode).d88" size="348304" crc="ab1128ca" sha1="83bc1d6db510553be4aeec800209e3bb529a2fb0"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="[utility] n80 and n88 disk basic utility collection (disk 2 - n88 mode #1).d88" size="348848" crc="8b8a9f73" sha1="0296440ad00804a559027a61e099410565d8eff4"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="[utility] n80 and n88 disk basic utility collection (disk 3 - n88 mode #2).d88" size="348848" crc="156e257a" sha1="d525cc3ccc6684841608dd4d4aa4c435948fa691"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="348848">
				<rom name="[utility] n80 and n88 disk basic utility collection (disk 4 - n80 mode).d88" size="348848" crc="9a05a7e4" sha1="746947ebb38e28304cd431927a33cfd4d95370b2"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="591408">
				<rom name="[utility] n80 and n88 disk basic utility collection (disk 5).d88" size="591408" crc="08c6485e" sha1="7277009da28f955651896d6a779988910f08478e"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== mamedev/mame/hash/super6.xml
<?xml version="1.0"?>
<!--
license:CC0
-->
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="super6" description="ADC Super Six diskettes">

	<software name="cpm22">
		<description>CP/M 2.2</description>
		<year>198?</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="175545">
				<rom name="cpm22.imd" size="175545" crc="86aea137" sha1="61fdfaaedaf5f4945f51cfd7550efc3957860316"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="242555">
				<rom name="cpm22r.imd" size="242555" crc="6df9024e" sha1="9bed3f5742fb712a1af53a4b9bb10f7f9a5873b4"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="206359">
				<rom name="sbios256.imd" size="206359" crc="cef80a0c" sha1="9184c84a5d540f7d4a8a7fe4ef0b6c913e0af542"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="451102">
				<rom name="sbios_23.imd" size="451102" crc="eb4cdd6d" sha1="64585b03ea5a154caee00de08ef09dbd02415d9c"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="527061">
				<rom name="sbios_s6.imd" size="527061" crc="891cd9a9" sha1="cd9cfea2e1178084fd4c85fb873dedfbb4f41706"/>
			</dataarea>
		</part>
	</software>

	<software name="digi56">
		<description>digi56</description>
		<year>198?</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop" interface="floppy_5_25">
			<dataarea name="flop" size="472732">
				<rom name="digi56.imd" size="472732" crc="b31a174c" sha1="7e7e99e24032d96c5823c1345c55101cf1d2ca2c"/>
			</dataarea>
		</part>
	</software>

	<software name="tdos122p">
		<description>TurboDOS v1.22p</description>
		<year>198?</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="Operating system disk"/>
			<dataarea name="flop" size="205576">
				<rom name="12_1.imd" size="205576" crc="50ba328b" sha1="c40427b7286f8faec207e2a403c6a02e6172636d"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="Bootable disk"/>
			<dataarea name="flop" size="197706">
				<rom name="12_2.imd" size="197706" crc="88811af4" sha1="374b8e3b6463e19817fd55c2b57329487265fc85"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<feature name="part_id" value="Disk drivers disk"/>
			<dataarea name="flop" size="228565">
				<rom name="12_3.imd" size="228565" crc="928904ca" sha1="04667695851e30b89293a15fea702c1ab714fd33"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<feature name="part_id" value="Non-disk drivers disk"/>
			<dataarea name="flop" size="168239">
				<rom name="12_4.imd" size="168239" crc="917266c3" sha1="ec69d986abff8bf72289df3ad5e189a31715edb5"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<feature name="part_id" value="GEN, PAR and DOC files"/>
			<dataarea name="flop" size="180559">
				<rom name="12_5.imd" size="180559" crc="dcb7a3d5" sha1="7a0935bc8d18d7345eae52b055ed2cfd4137f7b5"/>
			</dataarea>
		</part>
	</software>

	<software name="tdos14">
		<description>TurboDOS v1.4</description>
		<year>1985</year>
		<publisher>Advanced Digital Corporation</publisher>
		<info name="protection" value="none" />
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="Primary"/>
			<dataarea name="flop" size="1033649">
				<rom name="14_1.imd" size="1033649" crc="082d934c" sha1="eb8ded42f87acb943ca970d692bc963f259c0be1"/>
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="GEN, PAR and DOC files"/>
			<dataarea name="flop" size="220201">
				<rom name="14_2.imd" size="220201" crc="3beb825f" sha1="70d6cefaae69bab3ef96ca84e662fdc81b2c7e6c"/>
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<feature name="part_id" value="Disk drivers disk"/>
			<dataarea name="flop" size="351139">
				<rom name="14_3.imd" size="351139" crc="cd7f9d60" sha1="07b2d33ceb2241c8d045120a50a77d18281d9797"/>
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<feature name="part_id" value="DPROG"/>
			<dataarea name="flop" size="407719">
				<rom name="14_4.imd" size="407719" crc="61bf5d11" sha1="2307ebd1ea7783780966aefde56c361e708ba549"/>
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<feature name="part_id" value="Backup"/>
			<dataarea name="flop" size="896541">
				<rom name="14_5.imd" size="896541" crc="1e1f7818" sha1="0f3a2f2ac6fd77e6e9ccf14a990e8e4f7dc527e1"/>
			</dataarea>
		</part>
		<part name="flop6" interface="floppy_5_25">
			<feature name="part_id" value="System disk"/>
			<dataarea name="flop" size="217116">
				<rom name="14_6.imd" size="217116" crc="aff49cce" sha1="f4bc3ba45a522082058bdc209d61c33fcd8466d3"/>
			</dataarea>
		</part>
		<part name="flop7" interface="floppy_5_25">
			<feature name="part_id" value="Generation disk"/>
			<dataarea name="flop" size="396137">
				<rom name="14_7.imd" size="396137" crc="5a81c9ce" sha1="e89281786973fd778656bfc72a4a4e174ea9efcd"/>
			</dataarea>
		</part>
		<part name="flop8" interface="floppy_5_25">
			<feature name="part_id" value="Deltasoft Multi User BASIC"/>
			<dataarea name="flop" size="152879">
				<rom name="14_8.imd" size="152879" crc="28e55937" sha1="23e1999e5a71ee36e04e142e28414d20182f6401"/>
			</dataarea>
		</part>
		<part name="flop9" interface="floppy_5_25">
			<dataarea name="flop" size="354469">
				<rom name="bios.imd" size="354469" crc="98188a65" sha1="5ab78191022cdfaf4aa28319770e7ab6e91eb737"/>
			</dataarea>
		</part>
		<part name="flop10" interface="floppy_5_25">
			<feature name="part_id" value="COM files, TurboSlave PAR+GEN files, boot tracks on disk"/>
			<dataarea name="flop" size="1036746">
				<rom name="slave.imd" size="1036746" crc="1602ab7c" sha1="5f75c227fb3b9a3838d0a60efab8c1b162638652"/>
			</dataarea>
		</part>
	</software>

</softwarelist>
