=== mamedev/mame/trunk/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
	<!ATTLIST softwarelist name CDATA #REQUIRED>
	<!ATTLIST softwarelist description CDATA #IMPLIED>
	<!ELEMENT software (description, year?, publisher, info*, sharedfeat*, part*)>
		<!ATTLIST software name CDATA #REQUIRED>
		<!ATTLIST software cloneof CDATA #IMPLIED>
		<!ATTLIST software supported (yes|partial|no) "yes">
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT info EMPTY>
			<!ATTLIST info name CDATA #REQUIRED>
			<!ATTLIST info value CDATA #IMPLIED>
		<!ELEMENT sharedfeat EMPTY>
			<!ATTLIST sharedfeat name CDATA #REQUIRED>
			<!ATTLIST sharedfeat value CDATA #IMPLIED>
		<!ELEMENT part (feature*, dataarea*, diskarea*, dipswitch*)>
			<!ATTLIST part name CDATA #REQUIRED>
			<!ATTLIST part interface CDATA #REQUIRED>
			<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
			<!ELEMENT feature EMPTY>
				<!ATTLIST feature name CDATA #REQUIRED>
				<!ATTLIST feature value CDATA #IMPLIED>
			<!ELEMENT dataarea (rom*)>
				<!ATTLIST dataarea name CDATA #REQUIRED>
				<!ATTLIST dataarea size CDATA #REQUIRED>
				<!ATTLIST dataarea databits (8|16|32|64) "8">
				<!ATTLIST dataarea endian (big|little) "little">
				<!ELEMENT rom EMPTY>
					<!ATTLIST rom name CDATA #IMPLIED>
					<!ATTLIST rom size CDATA #IMPLIED>
					<!ATTLIST rom crc CDATA #IMPLIED>
					<!ATTLIST rom sha1 CDATA #IMPLIED>
					<!ATTLIST rom offset CDATA #IMPLIED>
					<!ATTLIST rom value CDATA #IMPLIED>
					<!ATTLIST rom status (baddump|nodump|good) "good">
					<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>
			<!ELEMENT diskarea (disk*)>
				<!ATTLIST diskarea name CDATA #REQUIRED>
				<!ELEMENT disk EMPTY>
					<!ATTLIST disk name CDATA #REQUIRED>
					<!ATTLIST disk sha1 CDATA #IMPLIED>
					<!ATTLIST disk status (baddump|nodump|good) "good">
					<!ATTLIST disk writeable (yes|no) "no">
			<!ELEMENT dipswitch (dipvalue*)>
				<!ATTLIST dipswitch name CDATA #REQUIRED>
				<!ATTLIST dipswitch tag CDATA #REQUIRED>
				<!ATTLIST dipswitch mask CDATA #REQUIRED>
				<!ELEMENT dipvalue EMPTY>
					<!ATTLIST dipvalue name CDATA #REQUIRED>
					<!ATTLIST dipvalue value CDATA #REQUIRED>
					<!ATTLIST dipvalue default (yes|no) "no">

=== mamedev/mame/hash/tx0_ptp.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0
-->

<softwarelist name="tx0_ptp" description="TX-0 Paper Tape Reader images">
	<!-- The "8N" compatibility tag is used for programs written or reassembled after 1960, using the revised instruction code.
	     The encoding of "64" and "8O" programs is incompatible with the tx0_8kw system. These two categories may receive separate lists in the future.
	-->

	<software name="munching">
		<description>Munching Squares</description>
		<year>196?</year>
		<publisher>MIT</publisher>
		<info name="usage" value="Press read in switch, then restart after loader halts at 17777. Use TAC switches to vary display pattern."/>
		<sharedfeat name="compatibility" value="8N"/>
		<part name="ptp" interface="tx0_ptp">
			<feature name="blocks_used" value="20-52, 17756-17777"/>
			<dataarea name="ptap" size="327">
				<rom name="bin_munchingSquares.bin" size="327" crc="54afd9a3" sha1="a7fc6d62ea1cef21f1563cb8b86a5e63198af0ae"/>
			</dataarea>
		</part>
	</software>

	<software name="punchy">
		<description>Punchy</description>
		<year>195?</year>
		<publisher>MIT</publisher>
		<info name="author" value="John T. Gilmore, Jr."/>
		<info name="usage" value="Create file for punch device. Press read in switch, then restart after loader halts at 7777."/>
		<!-- For detailed usage instructions, see memorandum M-5001-1. -->
		<sharedfeat name="compatibility" value="64,8O"/>
		<part name="ptp" interface="tx0_ptp">
			<!-- Reconstructed from assembly listing dated "3 FEB" in handwriting, together with the standard tape input routine from M-5001-1.
			     This version is independent of UT-3, but does require that the aforementioned input routine remain in memory. -->
			<feature name="blocks_used" value="6547-7610, 7741-7777"/>
			<dataarea name="ptap" size="1821">
				<rom name="punchy.bin" size="1821" crc="3a0ead7e" sha1="6fb6f072251712cab2e614d1a80a626b9a27f1f2"/>
			</dataarea>
		</part>
	</software>

	<software name="ut3">
		<description>Utility Tape 3</description>
		<year>1958</year>
		<publisher>MIT</publisher>
		<info name="author" value="Charles Woodward"/>
		<info name="usage" value="Press read in switch, then wait for loader to finish before typing commands."/>
		<!-- Commands recognized: addr(ess), word, surp(ise), goto, pntv(ertical), pnth(orizontal), punc(h), inpu(t).
		     Subcommands recognized: cons(tants), inst(ructions).
		     The Trace tape optionally replaces pntv and pnth with new commands trac(e) and begi(n).
		     For detailed usage instructions, see memorandum M-5001-1. Note that the 'slash' character is |, not /. -->
		<sharedfeat name="compatibility" value="64,8O"/>
		<part name="ptp1" interface="tx0_ptp">
			<!-- Reconstructed from assembly listing dated "27 Feb 1958" in handwriting. The opcodes for 'rfa', 'rfl' and 'rfr'
			     are uncertain; it has been assumed that these are the "start PETR running" OPRs described in 6M-4789-1. -->
			<feature name="part_id" value="UT3"/>
			<feature name="blocks_used" value="5540-7611, 7622-7777"/>
			<dataarea name="ptap" size="3381">
				<rom name="ut3.bin" size="3381" crc="b287f67f" sha1="40ec0c15873dae9b139af3c6dc756268fa87f63d" status="baddump"/>
			</dataarea>
		</part>
		<part name="ptp2" interface="tx0_ptp">
			<!-- Reconstructed from undated assembly listing. -->
			<feature name="part_id" value="Trace"/>
			<feature name="blocks_used" value="6657-7160, 7316-7331"/>
			<dataarea name="ptap" size="642">
				<rom name="trace.bin" size="642" crc="b8850e4b" sha1="4345f24aeea472d5c357641d8a868e8326a015bc"/>
			</dataarea>
		</part>
	</software>

	<software name="ut3tra" cloneof="ut3">
		<description>Utility Tape 3 ('tra' modification)</description>
		<year>1959?</year>
		<publisher>MIT</publisher>
		<!-- Reconstructed from patches in appendix to UT3 assembly listing. This modification both supports and requires the new 'tra' instruction. -->
		<info name="usage" value="Press read in switch, then wait for loader to finish before typing commands."/>
		<sharedfeat name="compatibility" value="8O"/>
		<part name="ptp" interface="tx0_ptp">
			<feature name="blocks_used" value="5540-7611, 7622-7777"/>
			<dataarea name="ptap" size="3381">
				<rom name="ut3_tra.bin" size="3381" crc="a71f37a6" sha1="c60575cfe2cf0451660c846a927ad05747693ff5"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/cbm2_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="cbm2_cart" description="Commodore CBM-II cartridges">

	<software name="calcresu">
		<description>Calc Result</description>
		<year>198?</year>
		<publisher>Handic Software</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="calc_result-bx700.bin" size="0x2000" crc="4775ebb3" sha1="5c6928a9cd8a3ce6a1d11221292b832295d6543e" offset="0" />
			</dataarea>
		</part>

		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="1070662">
				<rom name="calc_result_700_bx_single_version_v1.0.d82" size="1070662" crc="244a2122" sha1="44661ed8e3307bb967f97ce1f5a247ca3cded0b3" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="profitxt">
		<description>ProfiText</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="profitext.bin" size="0x2000" crc="ac622a2b" sha1="a02fcd187b7493a08379bbaef3d4296a083d30c8" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="demo1">
		<description>Demo 1</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="cbm610-cart1-red-left.bin" size="0x2000" crc="be426f3d" sha1="da6f1099fd09165f8ee454e2e517cfc523deb8b7" offset="0" />
			</dataarea>

			<dataarea name="bank2" size="0x2000">
				<rom name="cbm610-cart1-blue-right.bin" size="0x2000" crc="61a5008b" sha1="02db07ca68631aefb69e5db41fada27486263c69" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="demo2">
		<description>Demo 2</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="cbm610-cart2-white-left.bin" size="0x2000" crc="aeb6881c" sha1="4bdabbd7d6d642f916b5a91155396c98fce591a3" offset="0" />
			</dataarea>

			<dataarea name="bank2" size="0x2000">
				<rom name="cbm610-cart2-green-right.bin" size="0x2000" crc="61a5008b" sha1="02db07ca68631aefb69e5db41fada27486263c69" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="moni610">
		<description>Moni610</description>
		<year>2008</year>
		<publisher>Ullrich von Bassewitz</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x2000">
				<rom name="moni.bin" size="0x2000" crc="43b08d1f" sha1="9c0c24907e85674348dd58e81e6da64e157e9d0f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="vt52">
		<description>VT52 Emulator</description>
		<year>1986</year>
		<publisher>&lt;unknown&gt;</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank2" size="0x2000">
				<rom name="vt52emu.bin" size="0x2000" crc="b3b6173a" sha1="dd4a412a1a6ce4272b02d731364dd6dc96a4570b" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="graphic">
		<description>High Resolution Graphics</description>
		<year>198?</year>
		<publisher>Commodore</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<feature name="slot" value="graphic" />

			<dataarea name="bank3" size="0x2000">
				<rom name="324688-01.bin" size="0x2000" crc="863e9ef8" sha1="d75ffa97b2dd4e1baefe4acaa130daae866ab0e8" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="wordresu">
		<description>Word Result</description>
		<year>198?</year>
		<publisher>Handic Software</publisher>
		
		<part name="cart" interface="cbm2_cart">
			<dataarea name="bank1" size="0x1000">
				<!-- this is the Commodore 64 character generator ROM, used as a copy protection dongle -->
				<rom name="901225-01.bin" size="0x1000" crc="ec4272ee" sha1="adc7c31e18c7c7413d54802ef2f4193da14711aa" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/mikrosha_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="mikrosha_cart" description="Mikrosha cartridges">

	<software name="micron">
		<description>BASIC-Micron, ED.Micron, Assembler</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="cart" interface="mikrosha_cart">
			<dataarea name="rom" size="16384">
				<rom name="micron.rom" size="16384" crc="42ac7739" sha1="ca7ac6e0f38d54274db14d1dd4141722908b2d8b"/>
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/mac_hdd.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0-1.0
-->
<softwarelist name="mac_hdd" description="Apple Macintosh hard disk images">
	<software name="mac608">
		<description>System Software 6.0.8</description>
		<year>1988</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac608" sha1="0eff82806f671484ec0c91cdc95ad90aa3157885" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac700">
		<description>System Software 7.0</description>
		<year>1991</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac700" sha1="a4c7777125331339afcd47dda5adca26ff57a427" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac701">
		<description>System Software 7.0.1</description>
		<year>1991</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac701" sha1="f867db45d7543ba87ca0e762bc920fe11d2a0753" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac711">
		<description>System Software 7.1.1</description>
		<year>1993</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac711" sha1="b1625378d1ba00861a07ebe47f4b6b54c849c61f" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac750">
		<description>System Software 7.5</description>
		<year>1994</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac750" sha1="9b59a611f0fddd560bc8b72c1dae07d0f2e10dcc" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac753">
		<description>System Software 7.5.3 Revision 2</description>
		<year>1996</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac753" sha1="757e4c69281993871bb7a199583f8f0c042c0ac7" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac755">
		<description>System Software 7.5.5</description>
		<year>1996</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac755" sha1="45990ff07419555d576eaa4f2293d62e74d055b6" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac760">
		<description>System Software 7.6</description>
		<year>1997</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac760" sha1="7e5ac00619dbf2395611f19658fab8e029d64bc7" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac761">
		<description>System Software 7.6.1</description>
		<year>1997</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac761" sha1="fa41734a26c37dea26f5d5590a8545afe26005ac" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac80">
		<description>Mac OS 8.0 (US English)</description>
		<year>1997</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac80" sha1="d1bcb1f3fc8bff56f95fc09e19a615d9d192ed4c" writeable="yes"/>
			</diskarea>
		</part>
	</software>
	<software name="mac81">
		<description>Mac OS 8.1 (US English)</description>
		<year>1998</year>
		<publisher>Apple</publisher>
		<part name="hdd" interface="hdd">
			<diskarea name="harddriv">
				<disk name="mac81" sha1="e9bedc463266fff9b5fb2121448be8adafebe2ae" writeable="yes"/>
			</diskarea>
		</part>
	</software>
</softwarelist>

=== mamedev/mame/hash/ngp.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--
license:CC0
-->
<softwarelist name="ngp" description="SNK Neo Geo Pocket cartridges">

<!-- Undumped:
NEOP00060 Dokodemo Mahjong
-->

	<!-- Developer: SNK -->
	<software name="bstars">
		<description>Pocket Sports Series - Baseball Stars (Euro, Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00070" />
		<info name="release" value="19981126 (JPN)" />
		<info name="alt_title" value="ポケットスポーツシリーズ ベースボール スターズ" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="baseball stars (japan, europe) (en,ja).bin" size="1048576" crc="4781ae84" sha1="8ece00f21ae49ed4777a9c990b2782465ef95380" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="kof_mlon">
		<description>King of Fighters R-1 &amp; Melon-chan no Seichou Nikki (Jpn, Prototype)</description>
		<year>199?</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00130" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="2097152">
				<rom name="king of fighters r-1 &amp; melon-chan no seichou nikki (japan) (beta).bin" size="2097152" crc="2660bfc4" sha1="a02d1b1113dbeac895832f1501029e40d9aab493" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: SNK -->
	<software name="kofr1">
		<description>Pocket Fighting Series - King of Fighters R-1 (Euro, Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00010" />
		<info name="release" value="19981028 (JPN)" />
		<info name="alt_title" value="ポケット格闘シリーズ キング・オブ・ファイターズ R-1" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="2097152">
				<rom name="king of fighters r-1 (japan, europe) (en,ja).bin" size="2097152" crc="dceb7e11" sha1="4a7adbcccb05b6047a38bb861523cbae7d956bfa" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: ADK -->
	<software name="melonchn">
		<description>Melon-chan no Seichou Nikki (Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00040" />
		<info name="release" value="19981028" />
		<info name="alt_title" value="めろんちゃんの成長日記" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="melon-chan no seichou nikki (japan).bin" size="1048576" crc="cb42cfa4" sha1="2dbf9c40ab0167ff172f10354d4674e5e6c901d5" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: Dyna -->
	<software name="neocher">
	<!-- NGPC, rated "Over 18" -->
		<description>Pocket Casino Series - Neo Cherry Master (Euro, Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00140" />
		<info name="release" value="19981225 (JPN)" />
		<info name="alt_title" value="ポケットカジノシリーズ ネオ・チェリーマスター" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="neo cherry master - real casino series (japan, europe) (en,ja).bin" size="1048576" crc="5c067579" sha1="c171d8d22d667d713bfc73c2b1c04bc77aacbb5c" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: SNK -->
	<software name="neocup98">
		<description>Pocket Sports Series - Neo Geo Cup '98 (Euro, Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00020" />
		<info name="release" value="19981028 (JPN)" />
		<info name="alt_title" value="ポケットスポーツシリーズ ネオジオカップ'98" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="1048576">
				<rom name="neo geo cup '98 (japan, europe) (en,ja).bin" size="1048576" crc="33add5bd" sha1="445743119c65a6765a0bdc849a12e9038192840c" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: Yumekobo -->
	<software name="ptennis">
		<description>Pocket Sports Series - Pocket Tennis (Euro, Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00090" />
		<info name="release" value="19981028 (JPN)" />
		<info name="alt_title" value="ポケットスポーツシリーズ ポケットテニス" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="524288">
				<rom name="pocket tennis - pocket sports series (japan, europe) (en,ja).bin" size="524288" crc="89410850" sha1="59602e44c631a00b2db53196204a4bc22ccd7025" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: SNK -->
	<software name="samsho">
	<!-- NGPC -->
		<description>Pocket Fighting Series - Samurai Spirit! (Jpn) ~ Samurai Shodown! (Euro)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00080" />
		<info name="release" value="19981225 (JPN)" />
		<info name="alt_title" value="ポケット格闘シリーズ サムライスピリッツ!" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="2097152">
				<rom name="samurai shodown - pocket fighting series (japan, europe) (en,ja).bin" size="2097152" crc="32e4696a" sha1="2c6adfa69e7aeada7d4198b373436eee35b70d01" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: ADK -->
	<software name="shougi">
		<description>Shougi no Tatsujin (Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00050" />
		<info name="release" value="19981120" />
		<info name="alt_title" value="将棋の達人" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="524288">
				<rom name="shougi no tatsujin (japan).bin" size="524288" crc="f34d0c9b" sha1="ab0c33236f72d2b317d91d034756b56cfca1b0b4" offset="000000" />
			</dataarea>
		</part>
	</software>

	<!-- Developer: Yumekobo -->
	<software name="tsunapn">
		<description>Renketsu Puzzle Tsunagete Pon! (Jpn)</description>
		<year>1998</year>
		<publisher>SNK</publisher>
		<info name="serial" value="NeoP00120" />
		<info name="release" value="19981028" />
		<info name="alt_title" value="連結パズル つなげてポンッ!" />
		<part name="cart" interface="ngp_cart">
			<dataarea name="rom" size="524288">
				<rom name="renketsu puzzle tsunagete pon (japan).bin" size="524288" crc="ce09f534" sha1="cbe53b08d03ef684c08fc6ee28fca168a3d091a7" offset="000000" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/abc80_cass.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="abc80_cass" description="Luxor ABC 80 cassettes">

	<software name="abcdemo">
		<description>ABCDemo</description>
		<year>2015</year>
		<publisher>Genesis Project</publisher>

		<part name="cass1" interface="abc80_cass">
			<dataarea name="cass" size="10793090">
				<rom name="genesisproject_abcdemo.wav" size="10793090" crc="7642349f" sha1="a0a808e9c9c5f3ca162ef22869600e1c735846c2" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== mamedev/mame/hash/p2k_cass.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<softwarelist name="p2k_cass" description="Philips P2000 cassettes">
	<software name="3ddool2">
		<description>3D Doolhof 2 (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="11520">
				<rom name="3d doolhof 2 (19xx)(-)(nl).cas" size="11520" crc="f3edc8b1" sha1="edc1f115be71029e91c0b617be8f35df1f921b81" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="brickwal">
		<description>Brick-Wall (Ned, v3.0)</description>
		<year>1982</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="17920">
				<rom name="brick-wall v3.0 (1982)(-)(nl).cas" size="17920" crc="b3d7ff52" sha1="ac0907cd223bd434262cfedb39a2b94ce4557820" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="componis">
		<description>Componist (Ned)</description>
		<year>1984</year>
		<publisher>A. Dobber</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="12800">
				<rom name="componist (1984)(a. dobber)(nl).cas" size="12800" crc="aadd88b3" sha1="72ba868d38b822e011b5145c95f0509529fa275e" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="elevator">
		<description>Elevator Humpie (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="7680">
				<rom name="elevator humpie (19xx)(-)(nl).cas" size="7680" crc="dd95644d" sha1="3dc8257bff5513b66e6b6566c7f8343817927d37" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="errsoft">
		<description>Ghost Hunter &amp; Racen (v2.0) (Ned)</description>
		<year>198?</year>
		<publisher>Errorsoft</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="25600">
				<rom name="ghost hunter (19xx)(errorsoft)(nl) &amp; racen v2.0 (19xx)(errorsoft)(nl).cas" size="25600" crc="4ddf2e30" sha1="c6421914a709ebc7a5ab920e76b1c076b35c3f89" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="kleuren">
		<description>Kleurendemonstratie (v3.9, Bad?)</description>
		<year>1983</year>
		<publisher>Klaas H.J. Roberts</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="15360">
				<rom name="kleurendemonstratie v3.9 (1983)(klaas h.j. roberts)[b].cas" size="15360" crc="45dd7e0f" sha1="f75ea81dd6c355c4ed0fd7a1b32374a5f2c00661" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="lazybug">
		<description>Lazy Bug (Ned, v6.0, Bad?)</description>
		<year>1985</year>
		<publisher>Double Brain</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="12800">
				<rom name="lazy bug v6.0 (1985)(double brain)(nl)[b].cas" size="12800" crc="8f322af1" sha1="d7b06d8c870098197efe1de079b30f16b03070a4" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="machoman">
		<description>Macho Man (v2.1, Bad?)</description>
		<year>1986</year>
		<publisher>J. Nieuwenhuizen</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="11520">
				<rom name="macho man v2.1 (1986)(j. nieuwenhuizen)[b].cas" size="11520" crc="1b2646fe" sha1="373430fa7e0a08dcd3483681c22d3c57c78bebe6" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="mkong">
		<description>Monkey Kong - Deel II (Ned, v1.0)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="11520">
				<rom name="monkey kong v1.0 deel ii (19xx)(-)(nl).cas" size="11520" crc="9a919e58" sha1="b7ae2607d6399d8fbb487dd61c7b382c10c2d1c6" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="snakey">
		<description>Snakeygame</description>
		<year>198?</year>
		<publisher>NOS - Thomas Hofmeister</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="7680">
				<rom name="snakeygame (19xx)(nos - thomas hofmeister).cas" size="7680" crc="3288dca2" sha1="2f6f0c55cb4dbd9f5dcb4ec8af41c8b3db0aaff8" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spaceatk">
		<description>Space Attack (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="14080">
				<rom name="space attack (19xx)(-)(nl).cas" size="14080" crc="39a8b855" sha1="2064084fb9dbc8afbee53f311bede4b252c3bd82" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spacef2">
		<description>Space Fight II - Fraxxon (v1.0)</description>
		<year>1985</year>
		<publisher>LBK Production</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="30720">
				<rom name="space fight ii - fraxxon v1.0 (1985)(lbk production).cas" size="30720" crc="e5e974bf" sha1="63f4478fa2b79a38a631b65559a3da36e4ce363f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spacef">
		<description>Space Fight (Ned, v3.0, Bad?)</description>
		<year>1984</year>
		<publisher>L.B. Kruijswijk</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="14080">
				<rom name="space fight v3.0 (1984)(l.b. kruijswijk)(nl)[b].cas" size="14080" crc="59091f51" sha1="7cf241b9debe8cae556a6412eee729fe3b846a4f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spacem">
		<description>Space Mission (Ned)</description>
		<year>1984</year>
		<publisher>P. v. H.</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="23040">
				<rom name="space mission (1984)(p. v. h.)(nl).cas" size="23040" crc="64907d33" sha1="5cb916c47f058efa221e3f8f2cfd3c91509a6015" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="spellpal">
		<description>Speelpaleis (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="15360">
				<rom name="speelpaleis (19xx)(-)(nl).cas" size="15360" crc="b46b537e" sha1="366abaaa4089d5603d63ea56ca89b01e7031c3e6" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="startrek">
		<description>Startrek (Ned)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="17920">
				<rom name="startrek (19xx)(-)(nl).cas" size="17920" crc="8480161f" sha1="7caf5c6f3d4dd3afdf2bb300b3253bc7a8b87351" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="vlucht">
		<description>Vlucht Simulator (Ned, Bad?)</description>
		<year>198?</year>
		<publisher>&lt;unknown&gt;</publisher>

		<part name="cass1" interface="p2k_cass">
			<dataarea name="cass" size="38400">
				<rom name="vlucht simulator (19xx)(-)(nl)[b].cas" size="38400" crc="74958e0a" sha1="9d1e83998549356ddc6dc2fcbc767462c82da833" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>
